### ISSUE TITLE
PEKA nie odświeża salda / nie może odświeżyć?

### ISSUE THREAD

**Issue by kczerniak** [shirou93/hacs-peka-poznan#1]

**Comment by kczerniak** [comment]
Siemka, integracja ma problem by ściągnąć poprawnie dane z PEKI, objawia się to w taki sposób:
![image](https://github.com/shirou93/hacs-peka-poznan/assets/33784141/b9b68638-d96b-4e32-8df0-00bb818d8840)

W loagach nie mam żadnych błędów :(

**Comment by shirou93** [comment]
> Siemka, integracja ma problem by ściągnąć poprawnie dane z PEKI, objawia się to w taki sposób:
> ![image](https://github.com/shirou93/hacs-peka-poznan/assets/33784141/b9b68638-d96b-4e32-8df0-00bb818d8840)
> 
> W loagach nie mam żadnych błędów :( 

Cześć, zerknij na stronie czy czasem nie masz capcha. Jak często odświeżasz stan? Ja przy 4h nie mam żadnych problemów.

**Comment by kczerniak** [comment]
Odświeżam w sumie co 6h, a przynajmniej próbuję, a na stronie, tak, przy logowaniu prosi o recapche

**Comment by shirou93** [comment]
> Odświeżam w sumie co 6h, a przynajmniej próbuję, a na stronie, tak, przy logowaniu prosi o capche 

Trzeba ją rozwiązać i po jakimś czasie powinna zniknąć. Chyba że jeszcze moje konto nie ma captchy i wdrożą ją u wszystkich na stałe.

Spróbuj ją rozwiązać wylogować i zrestartować ha.

**Comment by kczerniak** [comment]
Okej. chyba dla mnie kaplica, na stronie przy logowaniu za każdym razem prosi o recaptche, nic dziwnego że HA nie może się zalogować xD

**Comment by shirou93** [comment]
> Okej. chyba dla mnie kaplica, na stronie przy logowaniu za każdym razem prosi o recaptche, nic dziwnego że HA nie może się zalogować xD

Jak wdrożą to u mnie to będę mógł spróbować to ogarnąć. Na chwilę obecną nie mam jak ;)

**Comment by shirou93** [comment]
Możesz wysłać screena jakiego capcha używają?

**Comment by kczerniak** [comment]
![image](https://github.com/shirou93/hacs-peka-poznan/assets/33784141/4f1b514a-fc9f-4d94-867b-a3a4fd9b9721)

**Comment by kczerniak** [comment]
> > Okej. chyba dla mnie kaplica, na stronie przy logowaniu za każdym razem prosi o recaptche, nic dziwnego że HA nie może się zalogować xD
> 
> Jak wdrożą to u mnie to będę mógł spróbować to ogarnąć. Na chwilę obecną nie mam jak ;)

Nie no, jest to zrozumiałe, zatem będę czekał, bo jednak integracja fest pomocna była

**Comment by shirou93** [comment]
> > > Okej. chyba dla mnie kaplica, na stronie przy logowaniu za każdym razem prosi o recaptche, nic dziwnego że HA nie może się zalogować xD
> > 
> > 
> > Jak wdrożą to u mnie to będę mógł spróbować to ogarnąć. Na chwilę obecną nie mam jak ;)
> 
> Nie no, jest to zrozumiałe, zatem będę czekał, bo jednak integracja fest pomocna była

hej, rozwiąż captche. Usuń z hacs i zainstaluj ponownie. Zmień w configu jak masz login i hasło to wpisz bezpośrednio bez cudzysłowu. Zobaczymy czy zadziała. Sprawdziłem u siebie mając captche i zadziałało.

**Comment by kczerniak** [comment]
> > > > Okej. chyba dla mnie kaplica, na stronie przy logowaniu za każdym razem prosi o recaptche, nic dziwnego że HA nie może się zalogować xD
> > > 
> > > 
> > > Jak wdrożą to u mnie to będę mógł spróbować to ogarnąć. Na chwilę obecną nie mam jak ;)
> > 
> > 
> > Nie no, jest to zrozumiałe, zatem będę czekał, bo jednak integracja fest pomocna była
> 
> hej, rozwiąż captche. Usuń z hacs i zainstaluj ponownie. Zmień w configu jak masz login i hasło to wpisz bezpośrednio bez cudzysłowu. Zobaczymy czy zadziała. Sprawdziłem u siebie mając captche i zadziałało.

Siemka, logowanie w configu mam dodane za pomocą !secret więc nie było problemu cudzysłowów, i faktycznie, jak zalogowałem się na panel peki to sensor z automatu się odświeżył więc śmiga fest
